/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../node_modules/@syncfusion/ej2/styles/compatibility/material.css.ngstyle';
export const styles:any[] = ['.container {\r\n    padding-top: 75px;\r\n}\r\n\r\nej-reportviewer {\r\n    display: block;\r\n    height: 550px;\r\n}\r\n\r\n.e-reportviewer-pageview {\r\n    -webkit-box-sizing: content-box !important;\r\n    -moz-box-sizing: content-box !important;\r\n    box-sizing: content-box !important;\r\n}\r\n\r\n',
    i0.styles];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovU2FtcGxlL0dpdEh1Yi9UZXN0L2VqMS1lajItd2VicGFjay1jc3Mvc3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcy5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRTovU2FtcGxlL0dpdEh1Yi9UZXN0L2VqMS1lajItd2VicGFjay1jc3Mvc3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7OzsifQ==
