/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../node_modules/@syncfusion/ej2-ng-dropdowns/src/drop-down-list/dropdownlist.component.ngfactory';
import * as i3 from '@angular/forms';
import * as i4 from '@syncfusion/ej2-ng-dropdowns/src/drop-down-list/dropdownlist.component';
import * as i5 from '../../node_modules/ej-angular2/src/ej/reportviewer.component.ngfactory';
import * as i6 from 'ej-angular2/src/ej/reportviewer.component';
import * as i7 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),31,'main',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'h2',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['Essential JS 2 DropDownList '])),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          12,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵeld(16777216,
          (null as any),(null as any),9,'ej-dropdownlist',[['id','ddlelement'],['placeholder',
              'Select a game']],(null as any),(null as any),(null as any),i2.View_DropDownListComponent_0,
          i2.RenderType_DropDownListComponent)),i1.ɵprd(5120,(null as any),i3.NG_VALUE_ACCESSOR,
          (p0_0:any) => {
            return [p0_0];
          },[i4.DropDownListComponent]),i1.ɵdid(6537216,(null as any),7,i4.DropDownListComponent,
          [i1.ElementRef,i1.ViewContainerRef],{dataSource:[0,'dataSource'],placeholder:[1,
              'placeholder']},(null as any)),i1.ɵqud(335544320,1,{footerTemplate:0}),
      i1.ɵqud(335544320,2,{headerTemplate:0}),i1.ɵqud(335544320,3,{valueTemplate:0}),
      i1.ɵqud(335544320,4,{groupTemplate:0}),i1.ɵqud(335544320,5,{itemTemplate:0}),
      i1.ɵqud(335544320,6,{noRecordsTemplate:0}),i1.ɵqud(335544320,7,{actionFailureTemplate:0}),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),0,'br',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n\n    '])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['Essential JavaScript ReportViewer '])),
      (_l()(),i1.ɵted((null as any),['\n\n    '])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),2,'ej-reportviewer',[['id','reportViewer_Control']],(null as any),
          (null as any),(null as any),i5.View_ReportViewerComponent_0,i5.RenderType_ReportViewerComponent)),
      i1.ɵdid(8372224,(null as any),0,i6.ReportViewerComponent,[i1.ElementRef,i1.ChangeDetectorRef,
          i1.IterableDiffers,i1.KeyValueDiffers],{reportPath_input:[0,'reportPath_input'],
          reportServiceUrl_input:[1,'reportServiceUrl_input']},(null as any)),(_l()(),
          i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),['\n\n    '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i7.AppComponent = _v.component;
    const currVal_0:any = _co.data;
    const currVal_1:any = 'Select a game';
    _ck(_v,9,0,currVal_0,currVal_1);
    const currVal_2:any = _co.reportPath;
    const currVal_3:any = _co.serviceUrl;
    _ck(_v,27,0,currVal_2,currVal_3);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'seed-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(49152,(null as any),0,i7.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i7.AppComponent> = i1.ɵccf('seed-app',
    i7.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovU2FtcGxlL0dpdEh1Yi9UZXN0L2VqMS1lajItd2VicGFjay1jc3Mvc3JjL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0U6L1NhbXBsZS9HaXRIdWIvVGVzdC9lajEtZWoyLXdlYnBhY2stY3NzL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0U6L1NhbXBsZS9HaXRIdWIvVGVzdC9lajEtZWoyLXdlYnBhY2stY3NzL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRTovU2FtcGxlL0dpdEh1Yi9UZXN0L2VqMS1lajItd2VicGFjay1jc3Mvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxtYWluIGNsYXNzPVwiY29udGFpbmVyXCI+XHJcbiAgICA8aDI+RXNzZW50aWFsIEpTIDIgRHJvcERvd25MaXN0IDwvaDI+XHJcbiAgICA8ZGl2PlxyXG4gICAgICAgIDxlai1kcm9wZG93bmxpc3QgaWQ9J2RkbGVsZW1lbnQnIFtkYXRhU291cmNlXT0nZGF0YScgcGxhY2Vob2xkZXI9J1NlbGVjdCBhIGdhbWUnPjwvZWotZHJvcGRvd25saXN0PlxyXG4gICAgPC9kaXY+XHJcbiAgICA8YnI+XHJcbiAgICA8aHIvPlxyXG5cclxuICAgIDxoMj5Fc3NlbnRpYWwgSmF2YVNjcmlwdCBSZXBvcnRWaWV3ZXIgPC9oMj5cclxuXHJcbiAgICA8ZWotcmVwb3J0dmlld2VyIGlkPVwicmVwb3J0Vmlld2VyX0NvbnRyb2xcIiBbcmVwb3J0U2VydmljZVVybF09XCJzZXJ2aWNlVXJsXCIgW3JlcG9ydFBhdGhdPVwicmVwb3J0UGF0aFwiPlxyXG4gICAgPC9lai1yZXBvcnR2aWV3ZXI+XHJcblxyXG4gICAgPGhyLz5cclxuPC9tYWluPiIsIjxzZWVkLWFwcD48L3NlZWQtYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBd0IsMkNBQ3BCO1VBQUE7VUFBQSxnQkFBSTtNQUFpQywyQ0FDckM7VUFBQTtVQUFBLGdCQUFLLCtDQUNEO1VBQUE7Y0FBQTs2Q0FBQTtVQUFBO1lBQUE7VUFBQSxxQ0FBQTtVQUFBO2NBQUE7YUFBQTthQUFBO2FBQUE7TUFBbUcsMkNBQ2pHO01BQ047VUFBQSwwREFBSTtVQUFBLGFBQ0o7VUFBQTtNQUFLLDZDQUVMO1VBQUE7VUFBQSw4QkFBSTtNQUF1Qyw2Q0FFM0M7VUFBQTtVQUFBO2FBQUE7K0NBQUE7VUFBQSxvRUFBcUc7aUJBQUEsNEJBQ25GO01BRWxCO1VBQUEsMERBQUs7VUFBQTs7SUFWZ0M7SUFBb0I7SUFBckQsV0FBaUMsVUFBb0IsU0FBckQ7SUFPdUU7SUFBaEM7SUFBM0MsWUFBMkUsVUFBaEMsU0FBM0M7Ozs7b0JDVko7TUFBQTthQUFBOzs7OyJ9
