/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
import * as i0 from '../../node_modules/@syncfusion/ej2/styles/compatibility/material.css.ngstyle';
export var styles = ['.container {\r\n    padding-top: 75px;\r\n}\r\n\r\nej-reportviewer {\r\n    display: block;\r\n    height: 550px;\r\n}\r\n\r\n.e-reportviewer-pageview {\r\n    -webkit-box-sizing: content-box !important;\r\n    -moz-box-sizing: content-box !important;\r\n    box-sizing: content-box !important;\r\n}\r\n\r\n',
    i0.styles];
//# sourceMappingURL=app.component.css.ngstyle.js.map